/*
 *   Copyright (c) 2023 
 *   All rights reserved.
 */
const audio = {
    SET_AUDIO: 'SET_AUDIO',
    CHANGE_VOLUME: 'CHANGE_VOLUME',
    SEEK_AUDIO: 'SEEK_AUDIO',
    SEEK_AUDIO_RESET: 'SEEK_AUDIO_RESET',
    SET_CURRENT_TRACK: 'SET_CURRENT_TRACK',
    CHANGE_CURRENT_TIME: 'CHANGE_CURRENT_TIME',
    PAUSE_TRACK: 'PAUSE_TRACK',
    PLAY_TRACK: 'PLAY_TRACK',
    PLAY_PLAYLIST: 'PLAY_PLAYLIST',
    SET_REPEAT: 'SET_REPEAT',
    REPEAT_TRACK: 'REPEAT_TRACK',
    REPEAT_PLAYLIST: 'REPEAT_PLAYLIST',
}
export default audio;