/*
 *   Copyright (c) 2023 
 *   All rights reserved.
 */
const playlist = {
    GET_PLAYLIST: 'GET_PLAYLIST',
    GET_PLAYLIST_FAILED: 'GET_PLAYLIST_FAILED',
    CREATE_PLAYLIST: 'CREATE_PLAYLIST',
    CREATE_PLAYLIST_FAILED: 'CREATE_PLAYLIST_FAILED',
    DELETE_PLAYLIST: 'DELETE_PLAYLIST',
    DELETE_PLAYLIST_FAILED: 'DELETE_PLAYLIST_FAILED',
    UPDATE_PLAYLIST: 'UPDATE_PLAYLIST',
}
export default playlist;